### ISSUE TITLE
Undefined property: App\Http\Controllers\SocialController::$buffer

### ISSUE THREAD

**Issue by Sjoerrdd** [mbarwick83/buffer#1]
Hello,
I'm trying to get the profile.json, but I'm getting the following error:

`Undefined property: App\Http\Controllers\SocialController::$buffer`

My code:
```
public function post(Buffer $buffer) {
      $user_profiles = $this->buffer->get('1/profiles.json', ['access_token' => 'imnotgoingpostthishere']);
      return $user_profiles;
    }
```

**Comment by mbarwick83** [comment]
This has nothing to do with the package. Make sure you're injecting the Buffer class properly. i.e. `use Mbarwick83\Buffer\Buffer`, etc.
